# Site settings
title: Frisco Epoxy Flooring
description: "Frisco's #1 Epoxy Coatings Company"
baseurl: "" # Empty because your site is at the root of your custom domain
url: "https://www.friscoepoxy.com" # Your custom domain

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
